import pytest
from main import is_dangerous

# Test cases for is_dangerous function (91 dangerous, 88 safe)
@pytest.mark.parametrize("command,expected", [
    # ---------- 71 Dangerous Commands ----------
    ("sudo rm -rf /", True),
    ("Sudo", True),
    ("Rm -Rf /", True),
    ("rm --no-preserve-root -rf /", True),
    ("rm -rf /tmp/test", True),
    ("rm -r /home/user/*", True),
    ("rm -f secret.txt", True),
    ("unlink important.db", True),
    ("sudo mkfs.ext4 /dev/sda1", True),
    ("mkfs.btrfs /dev/sdb2", True),
    ("mkfs.xfs /dev/nvme0n1p1", True),
    ("parted /dev/sda mklabel gpt", True),
    ("fdisk /dev/sdb", True),
    ("cfdisk /dev/sdc", True),
    ("sgdisk --zap-all /dev/sda", True),
    ("sfdisk --delete /dev/sdb", True),
    ("dd if=/dev/zero of=/dev/sda bs=1M", True),
    ("dd of=/dev/nvme0n1", True),
    ("cat /dev/zero > /dev/sda", True),
    ("cat /dev/random > file.img", True),
    ("yes > /dev/sdb", True),
    ("wipefs -a /dev/sda", True),
    ("shred -n 3 -v /dev/sdb1", True),
    ("wipe /dev/sdb1", True),
    ("srm -rf secrets/", True),
    (":(){ :|:& };:", True),
    ("fork bomb", True),
    ("kill -9 1", True),
    ("killall -9 python3", True),
    ("pkill -9 sshd", True),
    ("shutdown now", True),
    ("reboot", True),
    ("poweroff", True),
    ("halt", True),
    ("init 0", True),
    ("init 6", True),
    ("systemctl reboot", True),
    ("systemctl poweroff", True),
    ("chmod 777 /", True),
    ("chmod -R 777 /var/www", True),
    ("chown -R root:root /", True),
    ("chgrp -R wheel /etc", True),
    ("setfacl -bR /", True),
    ("iptables -F", True),
    ("iptables --flush", True),
    ("sudo iptables -F", True),
    ("ufw disable", True),
    ("ufw reset", True),
    ("firewalld stop", True),
    ("nft flush ruleset", True),
    ("ip route flush table main", True),
    ("echo > /etc/passwd", True),
    (">: /etc/shadow", True),
    ("ln -sf /dev/null /etc/passwd", True),
    ("mv /bin /tmp", True),
    ("mv /boot /backup", True),
    ("mv /etc /tmp/etc", True),
    ("mv /lib /tmp/lib", True),
    ("mv /usr /offline", True),
    ("mv /var /old_var", True),
    ("while true; do echo hi; done", True),
    ("for ((;;)); do :; done", True),
    ("yes | rm -rf /", True),
    ("tar cf /dev/sda backup.tar", True),
    ("gzip -c file > /dev/sda", True),
    ("bzip2 -c file > /dev/sdb", True),
    ("xz -c file > /dev/sdb", True),
    ("umount /", True),
    ("mount /dev/sda1 /mnt", True),
    ("grub-install /dev/sda", True),
    ("update-grub", True),
    ("history -c", True),
    ("rm ~/.bash_history", True),
    ("unset HISTFILE", True),
    ("dd if=/dev/random of=/dev/sda bs=4M", True),
    ("cryptsetup luksErase /dev/sdb1", True),
    ("cryptsetup close myvolume", True),
    ("vgremove vgdata", True),
    ("lvremove /dev/vgdata/lv0", True),
    ("pvremove /dev/sdb2", True),
    ("zpool destroy mypool", True),
    ("btrfs subvolume delete /mnt/subvol", True),
    ("xfs_admin -L newlabel -d /dev/sda1", True),
    ("mdadm --zero-superblock /dev/md0", True),
    ("cd /home/user", True),
    ("exec rm -rf /", True),
    ("exec rm -rf /", True),
    ("exec shred -n 3 /dev/sda", True),
    ("exec mkfs.ext4 /dev/sdb1", True),
    ("exec dd if=/dev/zero of=/dev/sdc bs=1M", True),
    ("exec /tmp/malicious_script.sh", True),
    ('exec echo "Hello World"', True),
    # ("docker system prune -a", True),
    # ("docker rm -f $(docker ps -aq)", True),
    # ("kubectl delete --all pods", True),
    # ("helm uninstall --all myrelease", True),
    # ("aws s3 rb s3://bucket --force", True),
    # ("gcloud compute disks delete --quiet disk-1", True),
    # ("az group delete --name mygroup --yes", True),
    # ("terraform destroy -auto-approve", True),
    # ("ansible-playbook site.yml --tags destroy", True),
    # ("salt '*' state.apply destroy", True),
    # ("chef-client -o destroy", True),
    # ("fabric abort", True),

    # ---------- Safe Commands ----------
    ('echo "Donald J. Trump is the 45th President of the United States, serving from January 20, 2017 to January 20, 2021." > donald.txt', False),
    ('echo "He was born on June 14, 1946 in Queens, New York City." >> donald_trump.txt', False),
    ("ls -la", False),
    ("pwd", False),
    ("echo hello world", False),
    ("mkdir new_folder", False),
    ("touch file.txt", False),
    ("cat file.txt", False),
    ("grep 'pattern' file.txt", False),
    ("find . -name '*.py' -type f", False),
    ("tar czf archive.tar.gz folder/", False),
    ("tar xzf archive.tar.gz", False),
    ("gzip file.txt", False),
    ("gunzip file.txt.gz", False),
    ("bzip2 file.txt", False),
    ("bunzip2 file.txt.bz2", False),
    ("xz file.txt", False),
    ("unxz file.txt.xz", False),
    ("scp file user@host:/path", False),
    ("rsync -av src/ dest/", False),
    ("docker ps", False),
    ("docker images", False),
    ("docker run hello-world", False),
    ("git status", False),
    ("git checkout main", False),
    ("git pull origin main", False),
    ("git push origin feature", False),
    ("git commit -m 'msg'", False),
    ("python3 script.py", False),
    ("python3 -m venv venv", False),
    ("pip install requests", False),
    ("pip3 install --user numpy", False),
    ("npm install", False),
    ("npm update", False),
    ("composer install", False),
    ("composer update", False),
    ("mysql -u user -p dbname < dump.sql", False),
    ("ps aux | grep python", False),
    ("top", False),
    ("htop", False),
    ("uname -a", False),
    ("df -h", False),
    ("du -sh *", False),
    ("free -m", False),
    ("uptime", False),
    ("whoami", False),
    ("date", False),
    ("cal", False),
    ("echo $PATH", False),
    ("export VAR=value", False),
    ("alias ll='ls -la'", False),
    ("curl http://example.com", False),
    ("wget http://example.com", False),
    ("ping -c 4 8.8.8.8", False),
    ("traceroute 8.8.8.8", False),
    ("netstat -tuln", False),
    ("ss -tuln", False),
    ("journalctl -xe", False),
    ("systemctl status sshd", False),
    ("service apache2 start", False),
    ("service apache2 stop", False),
    ("journalctl -u apache2", False),
    ("docker-compose up -d", False),
    ("kubectl get pods", False),
    ("helm list", False),
    ("aws s3 ls", False),
    ("gcloud compute instances list", False),
    ("az vm list", False),
    ("terraform plan", False),
    ("ansible --version", False),
    ("salt --versions-report", False),
    ("chef --version", False),
    ("fabric --version", False),
    ("node --version", False),
    ("npm --version", False),
    ("java -version", False),
    ("javac -version", False),
    ("go version", False),
    ("rustc --version", False),
    ("cargo --version", False),
    ("dotnet --info", False),
    ("mvn clean install", False),
    ("gradle build", False),
    ("psql -U user dbname", False),
    ("redis-cli ping", False),
    ("mongo --eval 'db.version()'", False),
    ("mysqladmin status", False),
    ("sqlite3 test.db 'SELECT * FROM table;'", False),
])

def test_is_dangerous(command, expected):
    assert is_dangerous(command) == expected
